### ISSUE TITLE
Any comment about upcoming Git Rev News edition 100

### ISSUE THREAD

**Issue by chriscool** [git/git.github.io#647] opened 2023-05-31 20:29 UTC
A currently mostly empty draft is there:

https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-100.md

Yeah, edition 100!!!

Feel free to comment in this issue, suggest topics, suggest persons to interview, or use the edit button (that looks like a pen) to edit and create a pull request with the changes you would like.

Let's try to publish this edition on Wednesday June 28th 2023!

Thanks!

cc @jnareb @mjaix @sivaraam @gitster

**Comment by jnareb** [comment] 2023-06-08 21:57
By the way, were any students accepted to work on Git for Google Summer of Code 2023? There were no announcement in the previous edition...

**Comment by chriscool** [comment] 2023-06-08 22:12
Yeah, some students have been accepted but I forgot to talk about this in the previous edition. I will write something in this edition. Thanks!

**Comment by sivaraam** [comment] 2023-06-17 19:38
@chriscool I found some time to add details regarding selected GSoC contributors to this edition via MR #648. Hope that's fine :-)

**Comment by chriscool** [comment] 2023-06-18 20:35
@sivaraam great! Thanks for both!

**Comment by chriscool** [comment] 2023-06-28 20:28
Draft sent: https://lore.kernel.org/git/CAP8UFD0cDwFE-i16w0gabyVv9fUfxSUAznnK84wLdNzit_NopA@mail.gmail.com/

**Comment by mjaix** [comment] 2023-06-29 19:03
Fixed some tiny spelling issues in ef0218c last night ... - the biggest
problem being a VDSL reconnect :-).

**Comment by jnareb** [comment] 2023-06-30 00:15
I wonder if the following links are worth adding:

- [Meet GitLab Duo, the suite of AI capabilities powering your workflows](https://about.gitlab.com/blog/2023/06/22/meet-gitlab-duo-the-suite-of-ai-capabilities/)
- [Crafting a better, faster GitHub Code View](https://github.blog/2023-06-21-crafting-a-better-faster-code-view/)

**Comment by jnareb** [comment] 2023-06-30 00:44
My links have landed in cd88153

**Comment by chriscool** [comment] 2023-06-30 10:10
@jnareb thanks for your links!

I think that the two links about GitLab Duo and GitHub Code Review are worth adding.

(Maybe you could also be interested in this GitLab Office Hours video about the Gitaly/Git team where I host a live coding session developing a small feature in Git: https://www.youtube.com/watch?v=INvu3C5oZWE)

**Comment by chriscool** [comment] 2023-06-30 10:13
@mjaix thanks for your fixes! They all look good to me.

**Comment by jnareb** [comment] 2023-06-30 13:25
> I think that the two links about GitLab Duo and GitHub Code Review are worth adding.
> 
> (Maybe you could also be interested in this GitLab Office Hours video about the Gitaly/Git team where I host a live coding session developing a small feature in Git: https://www.youtube.com/watch?v=INvu3C5oZWE)

@chriscool I have added both those 2 links, and the link to GitLab Office Hours video in  271e2e0 and 92bc8f9, respectively.

**Comment by jnareb** [comment] 2023-06-30 14:07
Short summary of those 11 responses to the Git Rev News Reader Survey in 3d060d1 .
Please check it for clarity, readability, and errors. Thanks in advance!

BTW. I can add more people to 'git' account on Survs.com (where the survey took place), if you want to analyze the result yourself. Or you can just read the report at <https://survs.com/report/72cqt0sbjw>, though it does not include the most interesting part (especially for the open-ended questions) - the actual responses. I can provide export of the result, in Excel, CSV, or SPSS format.

**Comment by mjaix** [comment] 2023-06-30 15:04
Reviewed the user survey report, deliberately changed the publication
date to 2023-06-30 and moved the Releases section to the end
in 66e92ec .
Regarding the survey suggestion "include a brief description of what is
in the link", I am not 100% convinced that I understand
what the contributor refers to - regarding the usage of links, my
personal feeling is that we are operating at the right level.

**Comment by jnareb** [comment] 2023-06-30 15:54
> Regarding the survey suggestion "include a brief description of what is in the link", I am not 100% convinced that I understand what the contributor refers to - regarding the usage of links, my personal feeling is that we are operating at the right level.

I think the issue is that sometimes the title of the link (the text of the link) is not enough to tell what is in the linked article, if it would be worth following the link or not. A sentence clarifying what is in there can help - from time to time I have had added such descriptions. But it takes effort and time...

**Comment by jnareb** [comment] 2023-06-30 15:56
> Reviewed the user survey report

Thank you very much, @mjaix - much appreciated.

**Comment by chriscool** [comment] 2023-06-30 19:45
@jnareb thanks for adding the 2 links and the link to the GitLab Office Hours video!

Thanks also for the summary of the first Survey results!

**Comment by chriscool** [comment] 2023-06-30 19:58
@mjaix thanks for the review of the survey report, thanks for changing the publication date to 2023-06-30, and thanks for moving the "Releases" section towards the end!

About changing the date, when doing that it's better to also do it in the "date: ..." metadata field too, as I just did in: dcd96fb29d57024cde39124690a5a0afc30ef0c9

About moving the Releases section, it's better to also change it in the template which is in the getreleases repo like I just did in:

https://github.com/chriscool/getreleases/commit/058265bf88bb9b9134ca9b55a86d055ddfaeb720

**Comment by chriscool** [comment] 2023-06-30 20:16
Published and announced in: https://lore.kernel.org/git/CAP8UFD3GX8or4bMf=2sBnpdTs4P2G=PdwRf3q+r2CLfNswTXXw@mail.gmail.com/

**Closed** 2023-07-28 12:48 UTC
