### ISSUE TITLE
Any comment about upcoming Git Rev News edition 91

### ISSUE THREAD

**Issue by chriscool** [git/git.github.io#598] opened 2022-09-02 21:25 UTC
A currently mostly empty draft is there:

https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-91.md

Feel free to comment in this issue, suggest topics, suggest persons to interview, or use the edit button (that looks like a pen) to edit and create a pull request with the changes you would like.

Let's try to publish this edition on Wednesday September 28th 2022!

Thanks!

cc @jnareb @mjaix @sivaraam @gitster

**Comment by jnareb** [comment] 2022-09-03 08:23
First part of links, originally intended for edition 90, landed in 8e6cac2

**Comment by chriscool** [comment] 2022-09-03 08:33
Thanks @jnareb for the links!

**Comment by jnareb** [comment] 2022-09-27 21:35
Second part of links, what was intended for edition 90 and some new links, landed in 7cacc81 .

It would be nice to have some writeup about **Git Merge 2022** event, and maybe also how our GSoC 2022 projects ended.

**Comment by chriscool** [comment] 2022-09-28 09:31
Thanks @jnareb for your links!

I agree that a writeup about the Git Merge 2022, and about our GSoC 2022 projects would be nice. I will try to add something about them!

**Comment by chriscool** [comment] 2022-09-28 09:31
Thanks @sivaraam and @peff for Peff's great interview!

**Comment by chriscool** [comment] 2022-09-29 04:34
@jnareb about the GSoC 2022 projects, the timeline of one of the projects (Reachability bitmap improvements) has been extended and the results haven't been officially announced to the contributor as the deadline for the Final Evaluation of this project is October 03, So it's not possible to provide a full write up at this time. Let's do it next month.

**Comment by chriscool** [comment] 2022-10-01 08:54
Draft sent: https://lore.kernel.org/git/CAP8UFD2pG7f5-9eywHE4ziz7OKLZ_A9AnNnQEQvdvOTYvsdP+A@mail.gmail.com/

This will be published today on October 1st (though the date on the page will be September 30th).

**Comment by mjaix** [comment] 2022-10-01 16:52
Hello Christian,

sorry for the delay on my side. I am proofreading the text right now.

**Comment by mjaix** [comment] 2022-10-01 19:28
Supplied my usual tiny fixes in f71dbc4.

**Comment by chriscool** [comment] 2022-10-01 19:54
@jnareb thanks for your fixes!

**Comment by chriscool** [comment] 2022-10-01 20:33
Edition published and announced in:

https://lore.kernel.org/git/CAP8UFD0_TLWTHpjwxgqAjBLpvBo5BntvpwRLqXrndYosEj7tHw@mail.gmail.com/

**Closed** 2022-10-19 12:08 UTC
