### ISSUE TITLE
Any comment about upcoming Git Rev News edition 117

### ISSUE THREAD

**Issue by chriscool** [git/git.github.io#737] opened 2024-11-01 21:06 UTC
A currently mostly empty draft is there:

https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-117.md

Feel free to comment in this issue, suggest topics, suggest persons to interview, or use the edit button (that looks like a pen) to edit and create a pull request with the changes you would like.

Let's try to publish this edition around the end of November 2024!

Thanks!

cc @jnareb @mjaix @sivaraam @gitster @stepnem

**Comment by chriscool** [comment] 2024-11-05 16:15
Thanks @dscho for the link!

**Comment by To1ne** [comment] 2024-11-13 14:09
[Mergiraf](https://mergiraf.org/) was [suggested](https://lore.kernel.org/git/a79eaccd-f309-4f62-a243-f8fdfd0f0e86@delpeuch.eu/) on the mailing list, it might be worth to include it.

cc @wetneb

**Comment by dscho** [comment] 2024-11-30 07:40
I just had a look at  https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-117.md and it didn't have any links yet... was it intentional to send out https://lore.kernel.org/git/CAP8UFD1R3Cp00KF2nAX6C5q=dtYLdaJKomXWM4DjM5DwjLi53w@mail.gmail.com/T/#u before those links were integrated?

**Comment by chriscool** [comment] 2024-11-30 21:20
@dscho yes, we send the draft email a few days before the end of each month even when @jnareb hasn't integrated the links. Hopefully he should integrate them soon.

**Comment by jnareb** [comment] 2024-11-30 23:56
Links have landed in a452810 .

- Thanks @To1ne and @wetneb for suggesting [Mergiraf](https://mergiraf.org/)
- Thanks @dscho for suggesting [How we shrunk our JavaScript monorepo git size by 94%](https://www.jonathancreamer.com/how-we-shrunk-our-git-repo-size-by-94-percent/)

**Comment by jnareb** [comment] 2024-12-01 03:18
The delay in sending links was, in part, caused by being busy with other work. One of the visible results of this other work is the [PatchScope](https://github.com/ncusi/PatchScope) app that just got made public. It is however in quite early stages of development.

In a bit of self promotion (I am one of its authors), I have added this app to links in f10de59 (separate commit, to make it easier to revert if deemed necessary).

**Comment by mjaix** [comment] 2024-12-01 21:15
***@***.*** [1]'s corrections  and supplied some additional tiny
corrections and rephrasings with 0e2d9c7 [2]. Please scrutinize.

[1] @stepnem https://github.com/stepnem
[2] 0e2d9c7
    https://github.com/git/git.github.io/commit/0e2d9c7ffb62c4965863c65c0c4b7ce67cbe3d36

**Comment by mjaix** [comment] 2024-12-01 21:18
** re-sent with correct sender **
***@***.*** [1]'s corrections  and supplied some additional tiny
corrections and rephrasings with 0e2d9c7 [2]. Please scrutinize.

[1] @stepnem https://github.com/stepnem
[2] 0e2d9c7
    https://github.com/git/git.github.io/commit/0e2d9c7ffb62c4965863c65c0c4b7ce67cbe3d36

**Comment by chriscool** [comment] 2024-12-01 21:36
Thanks @mjaix and @stepnem for the corrections and rephrasings!

**Comment by chriscool** [comment] 2024-12-01 21:36
Edition published and announced in: https://lore.kernel.org/git/CAP8UFD31OWebD5PXnCDVU-Sya8pY07bA2nsoskF50NUPhTcWZA@mail.gmail.com/

**Closed** 2024-12-13 13:22 UTC
